FROM ${base_image}

ARG http_proxy=http://child-prc.intel.com:913
ARG https_proxy=http://child-prc.intel.com:913

RUN mkdir /home/build
WORKDIR /home/build
RUN apt-get install wget -y
RUN wget ${whl_address}
RUN pip install ${whl_file} --force-reinstall





